version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_NAME=dbKmeans
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_PORT=5432
    volumes:
      - ./backend/data:/data # data klasörü
      - ./backend/log_file/app_errors.log:/log_file/app_errors.log

    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/frontend
    stdin_open: true
    tty: true

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: dbKmeans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
